project_id = "nbswprixtajseabjbrre"

[functions.analyze-property]
verify_jwt = true

[functions.parse-listing-data]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.create-stripe-checkout]
verify_jwt = false
