import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { PDFDocument, rgb, StandardFonts } from "https://esm.sh/pdf-lib@1.17.1";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface DealPackageRequest {
  lead_id: string;
  assignment_fee?: number;
  terms?: string;
}

function drawWrappedText(page: any, text: string, x: number, y: number, font: any, size: number, maxWidth: number, color: any) {
  const words = text.split(" ");
  let line = "";
  let currentY = y;
  for (const word of words) {
    const testLine = line + word + " ";
    if (font.widthOfTextAtSize(testLine, size) > maxWidth) {
      page.drawText(line.trim(), { x, y: currentY, size, font, color });
      currentY -= size + 4;
      line = word + " ";
    } else {
      line = testLine;
    }
  }
  if (line.trim()) {
    page.drawText(line.trim(), { x, y: currentY, size, font, color });
    currentY -= size + 4;
  }
  return currentY;
}

function drawSectionTitle(page: any, title: string, x: number, y: number, font: any, color: any, lineColor: any, width: number) {
  page.drawText(title, { x, y, size: 11, font, color });
  page.drawLine({ start: { x, y: y - 4 }, end: { x: x + width, y: y - 4 }, color: lineColor, thickness: 0.8 });
  return y - 20;
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { lead_id, assignment_fee, terms } = await req.json() as DealPackageRequest;
    if (!lead_id) {
      return new Response(JSON.stringify({ error: "lead_id is required" }), { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    const { data: lead, error: leadError } = await supabase
      .from("leads")
      .select("*, property:properties(*)")
      .eq("id", lead_id)
      .single();

    if (leadError || !lead) {
      return new Response(JSON.stringify({ error: "Lead not found" }), { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    const property = lead.property;
    const pdfDoc = await PDFDocument.create();
    const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
    const regular = await pdfDoc.embedFont(StandardFonts.Helvetica);

    const W = 612, H = 792, M = 50;
    const CW = W - M * 2;
    const primary = rgb(0.06, 0.45, 0.45);
    const darkText = rgb(0.12, 0.12, 0.12);
    const bodyText = rgb(0.25, 0.25, 0.25);
    const gray = rgb(0.5, 0.5, 0.5);
    const lightGray = rgb(0.85, 0.85, 0.85);
    const green = rgb(0.1, 0.5, 0.1);
    const red = rgb(0.7, 0.15, 0.15);
    const amber = rgb(0.75, 0.55, 0.0);
    const white = rgb(1, 1, 1);
    const bgLight = rgb(0.96, 0.98, 0.98);

    // ===== Helper to add footer =====
    function addFooter(pg: any) {
      pg.drawLine({ start: { x: M, y: 40 }, end: { x: W - M, y: 40 }, color: lightGray, thickness: 0.5 });
      pg.drawText("Confidential -- For qualified buyers only.", { x: M, y: 28, size: 7, font: regular, color: gray });
      pg.drawText("Generated by KLOSE", { x: W - M - bold.widthOfTextAtSize("Generated by KLOSE", 7), y: 28, size: 7, font: bold, color: primary });
    }

    // ===== PAGE 1: Property Overview & Contact =====
    let page = pdfDoc.addPage([W, H]);
    let y = H;

    // Header bar
    page.drawRectangle({ x: 0, y: H - 75, width: W, height: 75, color: primary });
    page.drawText("DEAL PACKAGE", { x: M, y: H - 38, size: 24, font: bold, color: white });
    page.drawText("KLOSE -- Investment Opportunity", { x: M, y: H - 56, size: 9, font: regular, color: rgb(0.78, 0.92, 0.92) });
    const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
    page.drawText(today, { x: W - M - regular.widthOfTextAtSize(today, 9), y: H - 38, size: 9, font: regular, color: white });

    y = H - 100;

    // --- K-Score Badge (top right) ---
    const piwScore = lead.piw_score || 0;
    const scoreColor = piwScore >= 75 ? green : piwScore >= 50 ? amber : gray;
    const prioLabel = piwScore >= 75 ? "HOT LEAD" : piwScore >= 50 ? "WARM LEAD" : "COLD LEAD";
    const badgeW = 120, badgeH = 40;
    const badgeX = W - M - badgeW;
    page.drawRectangle({ x: badgeX, y: y - 5, width: badgeW, height: badgeH, color: scoreColor });
    page.drawText(`K-Score ${piwScore}%`, { x: badgeX + 10, y: y + 17, size: 14, font: bold, color: white });
    page.drawText(prioLabel, { x: badgeX + 10, y: y + 3, size: 9, font: bold, color: white });

    // Property Address
    page.drawText("PROPERTY", { x: M, y: y + 25, size: 8, font: bold, color: gray });
    page.drawText(property?.address || "N/A", { x: M, y: y + 8, size: 18, font: bold, color: darkText });
    page.drawText(`${property?.city || ""}, ${property?.state || ""} ${property?.zip_code || ""}`, { x: M, y: y - 8, size: 11, font: regular, color: bodyText });
    if (property?.county) {
      page.drawText(`County: ${property.county}`, { x: M, y: y - 22, size: 9, font: regular, color: gray });
      y -= 55;
    } else {
      y -= 40;
    }

    // Divider
    page.drawLine({ start: { x: M, y }, end: { x: W - M, y }, color: lightGray, thickness: 1 });
    y -= 22;

    // --- OWNER & CONTACT ---
    y = drawSectionTitle(page, "OWNER & CONTACT", M, y, bold, primary, primary, CW);

    const ownerName = property?.owner_name || "Unknown";
    page.drawText(`Owner: ${ownerName}`, { x: M, y, size: 10, font: bold, color: darkText });
    if (property?.owner_type) {
      const ownerW = bold.widthOfTextAtSize(`Owner: ${ownerName}  `, 10);
      page.drawText(`(${property.owner_type})`, { x: M + ownerW, y, size: 9, font: regular, color: gray });
    }
    y -= 18;

    // Phones
    const phones = [
      { num: property?.owner_phone, type: property?.phone_1_type, dnc: property?.phone_1_dnc },
      { num: property?.phone_2, type: property?.phone_2_type, dnc: property?.phone_2_dnc },
      { num: property?.phone_3, type: property?.phone_3_type, dnc: property?.phone_3_dnc },
      { num: property?.phone_4, type: property?.phone_4_type, dnc: property?.phone_4_dnc },
      { num: property?.phone_5, type: property?.phone_5_type, dnc: property?.phone_5_dnc },
    ].filter(p => p.num);

    const contactablePhones = phones.filter(p => !p.dnc);

    if (phones.length > 0) {
      for (const p of phones) {
        const dncTag = p.dnc ? " [DNC - DO NOT CALL]" : "";
        const typeTag = p.type ? ` (${p.type})` : "";
        const label = p.dnc ? "x" : ">";
        page.drawText(`  ${label} ${p.num}${typeTag}${dncTag}`, { x: M, y, size: 9, font: p.dnc ? regular : bold, color: p.dnc ? red : bodyText });
        y -= 14;
      }
      if (contactablePhones.length === 0) {
        page.drawText("  ALL NUMBERS ARE DNC -- Consider direct mail only", { x: M, y, size: 9, font: bold, color: red });
        y -= 14;
      }
    } else {
      page.drawText("  NO PHONE -- Skip-tracing required", { x: M, y, size: 9, font: bold, color: red });
      y -= 14;
    }

    if (property?.owner_email) {
      page.drawText(`  Email: ${property.owner_email}`, { x: M, y, size: 9, font: regular, color: bodyText });
      y -= 14;
    }
    y -= 12;

    // --- FINANCIAL SUMMARY ---
    y = drawSectionTitle(page, "FINANCIAL SUMMARY", M, y, bold, primary, primary, CW);

    const arv = Number(property?.arv) || 0;
    const repairCost = Number(property?.repair_cost) || 0;
    const mao = property?.mao ? Number(property.mao) : (arv > 0 ? Math.round(arv * 0.7 - repairCost) : 0);
    const mortgageBalance = Number(property?.mortgage_balance) || 0;
    const netEquity = arv > 0 && mortgageBalance > 0 ? arv - mortgageBalance : 0;
    const equityPct = property?.equity_percent ? Number(property.equity_percent) : 0;
    const actualFee = assignment_fee || Number(lead.assignment_fee) || 0;
    const acqCost = Number(lead.offer_amount) || 0;
    const spread = mao > 0 && acqCost > 0 ? mao - acqCost : 0;
    const feeMin = spread > 0 ? Math.max(5000, Math.round(spread * 0.3)) : (actualFee > 0 ? actualFee : 0);
    const feeMax = spread > 0 ? Math.round(spread * 0.6) : (actualFee > 0 ? actualFee : 0);

    // Financial box
    const finBoxH = 100;
    page.drawRectangle({ x: M, y: y - finBoxH, width: CW, height: finBoxH, color: bgLight, borderColor: lightGray, borderWidth: 1 });

    const finData = [
      { label: "ARV", value: arv > 0 ? `$${arv.toLocaleString()}` : "TBD" },
      { label: "Repairs", value: repairCost > 0 ? `$${repairCost.toLocaleString()}` : "TBD" },
      { label: "MAO (70%)", value: mao > 0 ? `$${mao.toLocaleString()}` : "TBD" },
      { label: "Mortgage", value: mortgageBalance > 0 ? `$${mortgageBalance.toLocaleString()}` : "N/A" },
      { label: "Net Equity", value: netEquity > 0 ? `$${netEquity.toLocaleString()}` : "N/A" },
      { label: "Equity %", value: equityPct > 0 ? `${equityPct}%` : "N/A" },
      { label: "Our Offer", value: acqCost > 0 ? `$${acqCost.toLocaleString()}` : "Pending" },
      { label: "Spread", value: acqCost > 0 && spread !== 0 ? `$${spread.toLocaleString()}` : (acqCost === 0 ? "Set offer first" : "TBD") },
      { label: "Fee Range", value: feeMin > 0 ? `$${(feeMin/1000).toFixed(0)}K - $${(feeMax/1000).toFixed(0)}K` : (actualFee > 0 ? `$${actualFee.toLocaleString()}` : "Negotiable") },
    ];

    let col = 0, row = 0;
    for (const item of finData) {
      const xPos = M + 15 + col * (CW / 3);
      const yPos = y - 18 - row * 30;
      page.drawText(item.label, { x: xPos, y: yPos, size: 8, font: regular, color: gray });
      const valColor = item.label === "Spread" && spread > 0 ? green : item.label === "Spread" && spread < 0 ? red : darkText;
      page.drawText(item.value, { x: xPos, y: yPos - 12, size: 11, font: bold, color: valColor });
      col++;
      if (col >= 3) { col = 0; row++; }
    }
    y = y - finBoxH - 18;

    // --- MOTIVATION & URGENCY ---
    y = drawSectionTitle(page, "MOTIVATION & URGENCY SIGNALS", M, y, bold, primary, primary, CW);

    const signals: string[] = [];
    if (property?.is_foreclosure) signals.push("FORECLOSURE -- Property in pre-foreclosure/foreclosure");
    if (property?.auction_date) {
      const days = Math.ceil((new Date(property.auction_date).getTime() - Date.now()) / (1000*60*60*24));
      if (days > 0) signals.push(`AUCTION in ${days} days (${new Date(property.auction_date).toLocaleDateString()})`);
      else signals.push(`AUCTION EXPIRED (${new Date(property.auction_date).toLocaleDateString()})`);
    }
    if (property?.bk_date) signals.push(`BANKRUPTCY filed ${new Date(property.bk_date).toLocaleDateString()}`);
    if (property?.divorce_date) signals.push(`DIVORCE filed ${new Date(property.divorce_date).toLocaleDateString()}`);
    if (property?.is_vacant) signals.push("VACANT -- Property unoccupied");
    if (property?.tax_delinquent) signals.push(`TAX DELINQUENT${property.tax_debt ? ` ($${Number(property.tax_debt).toLocaleString()})` : ""}`);
    if (property?.is_probate) signals.push("PROBATE -- Estate/inheritance");
    if (property?.is_absentee_owner) signals.push(`ABSENTEE OWNER${property.absentee_type === 'out_of_state' ? ' (Out-of-State)' : ''}`);
    if (property?.owner_tenure_years && property.owner_tenure_years > 10) signals.push(`${property.owner_tenure_years}+ YEARS owned -- ownership fatigue`);
    if (property?.days_on_market && property.days_on_market > 90) signals.push(`${property.days_on_market} DAYS ON MARKET -- frustrated seller`);
    if (property?.equity_percent && Number(property.equity_percent) >= 100) signals.push("FREE & CLEAR -- No mortgage");
    if (property?.prefc_recording_date) signals.push(`Pre-FC Recorded: ${new Date(property.prefc_recording_date).toLocaleDateString()}`);
    if (property?.lien_type) signals.push(`LIEN: ${property.lien_type}${property.lien_amount ? ` ($${Number(property.lien_amount).toLocaleString()})` : ""}`);

    if (signals.length > 0) {
      // Draw urgency count badge
      const urgencyText = `${signals.length} distress signal(s) detected`;
      page.drawText(urgencyText, { x: M, y, size: 9, font: bold, color: signals.length >= 3 ? red : amber });
      y -= 16;
      for (const s of signals) {
        page.drawText(`  > ${s}`, { x: M, y, size: 9, font: regular, color: bodyText });
        y -= 13;
      }
    } else {
      page.drawText("No specific distress signals detected", { x: M, y, size: 9, font: regular, color: gray });
      y -= 13;
    }
    y -= 12;

    // --- PROPERTY DETAILS ---
    y = drawSectionTitle(page, "PROPERTY DETAILS", M, y, bold, primary, primary, CW);

    const details = [
      ["Type", (property?.property_type || "N/A").replace("_", " ").toUpperCase()],
      ["Year Built", property?.year_built?.toString() || "N/A"],
      ["Sqft", property?.sqft ? `${property.sqft.toLocaleString()}` : "N/A"],
      ["Bed/Bath", `${property?.bedrooms || "?"} / ${property?.bathrooms || "?"}`],
      ["Lot", property?.lot_size ? `${Number(property.lot_size).toLocaleString()} sqft` : "N/A"],
      ["Condition", property?.property_condition || property?.exterior_condition || "N/A"],
    ];
    col = 0; row = 0;
    for (const [label, value] of details) {
      const xPos = M + col * (CW / 3);
      const yPos = y - row * 24;
      page.drawText(`${label}:`, { x: xPos, y: yPos, size: 9, font: regular, color: gray });
      page.drawText(value, { x: xPos + 60, y: yPos, size: 9, font: bold, color: darkText });
      col++;
      if (col >= 3) { col = 0; row++; }
    }
    y = y - Math.ceil(details.length / 3) * 24 - 12;

    // --- MLS AGENT (if exists) ---
    if (property?.mls_agent_name) {
      y = drawSectionTitle(page, "MLS AGENT", M, y, bold, primary, primary, CW);
      let agentLine = property.mls_agent_name;
      if (property.mls_agent_phone) agentLine += ` | ${property.mls_agent_phone}`;
      page.drawText(agentLine, { x: M, y, size: 9, font: bold, color: bodyText });
      y -= 14;
      if (property.mls_agent_email) {
        page.drawText(property.mls_agent_email, { x: M, y, size: 9, font: regular, color: bodyText });
        y -= 14;
      }
    }

    addFooter(page);

    // ===== PAGE 2: Offer Strategy & Terms =====
    let page2 = pdfDoc.addPage([W, H]);
    let y2 = H;

    // Header bar (smaller)
    page2.drawRectangle({ x: 0, y: H - 50, width: W, height: 50, color: primary });
    page2.drawText("OFFER STRATEGY & TERMS", { x: M, y: H - 32, size: 18, font: bold, color: white });
    page2.drawText(property?.address || "", { x: W - M - regular.widthOfTextAtSize(property?.address || "", 9), y: H - 32, size: 9, font: regular, color: white });

    y2 = H - 80;

    // --- RECOMMENDED OFFER STRATEGY ---
    y2 = drawSectionTitle(page2, "RECOMMENDED OFFER STRATEGY", M, y2, bold, primary, primary, CW);

    if (mao > 0) {
      const offerStart = acqCost > 0 ? acqCost : Math.round(mao * 0.85);
      const offerMax = mao;
      const displaySpread = spread;

      // Offer range box
      const offerBoxH = 90;
      page2.drawRectangle({ x: M, y: y2 - offerBoxH, width: CW, height: offerBoxH, color: bgLight, borderColor: green, borderWidth: 1.5 });

      page2.drawText("START OFFER AT:", { x: M + 15, y: y2 - 20, size: 9, font: regular, color: gray });
      page2.drawText(`$${offerStart.toLocaleString()}`, { x: M + 15, y: y2 - 36, size: 16, font: bold, color: green });

      page2.drawText("MAX OFFER (MAO):", { x: M + CW / 3 + 10, y: y2 - 20, size: 9, font: regular, color: gray });
      page2.drawText(`$${offerMax.toLocaleString()}`, { x: M + CW / 3 + 10, y: y2 - 36, size: 16, font: bold, color: darkText });

      if (feeMin > 0) {
        page2.drawText("YOUR PROFIT:", { x: M + (CW * 2 / 3) + 10, y: y2 - 20, size: 9, font: regular, color: gray });
        page2.drawText(`$${(feeMin/1000).toFixed(0)}K - $${(feeMax/1000).toFixed(0)}K`, { x: M + (CW * 2 / 3) + 10, y: y2 - 36, size: 16, font: bold, color: green });
      }

      // Negotiation tips
      page2.drawText("NEGOTIATION LEVERAGE:", { x: M + 15, y: y2 - 58, size: 8, font: bold, color: primary });
      let leverageText = `${signals.length} distress signal(s)`;
      if (property?.auction_date) {
        const days = Math.ceil((new Date(property.auction_date).getTime() - Date.now()) / (1000*60*60*24));
        if (days > 0) leverageText += ` | Auction deadline: ${days} days`;
      }
      if (equityPct > 0) leverageText += ` | Equity: ${equityPct}%`;
      page2.drawText(leverageText, { x: M + 15, y: y2 - 72, size: 8, font: regular, color: bodyText });

      y2 = y2 - offerBoxH - 25;
    } else {
      page2.drawText("Insufficient data to calculate offer strategy.", { x: M, y: y2, size: 10, font: regular, color: gray });
      page2.drawText("Ensure ARV and acquisition cost are entered to generate recommendations.", { x: M, y: y2 - 16, size: 9, font: regular, color: gray });
      y2 -= 50;
    }

    // --- DEAL BREAKDOWN ---
    y2 = drawSectionTitle(page2, "DEAL BREAKDOWN", M, y2, bold, primary, primary, CW);

    const breakdownItems = [
      { label: "After Repair Value (ARV)", value: arv > 0 ? `$${arv.toLocaleString()}` : "TBD", note: "Estimated market value after full rehab" },
      { label: "x 70% Rule", value: arv > 0 ? `$${Math.round(arv * 0.7).toLocaleString()}` : "TBD", note: "Standard investor discount" },
      { label: "- Repair Cost", value: repairCost > 0 ? `$${repairCost.toLocaleString()}` : "TBD", note: "Estimated rehab budget" },
      { label: "= MAO", value: mao > 0 ? `$${mao.toLocaleString()}` : "TBD", note: "Maximum Allowable Offer" },
      { label: "- Our Offer", value: acqCost > 0 ? `$${acqCost.toLocaleString()}` : "Pending", note: "Your contract price with seller" },
      { label: "= Spread", value: acqCost > 0 && spread !== 0 ? `$${spread.toLocaleString()}` : "Pending", note: "Available margin for assignment" },
    ];

    for (const item of breakdownItems) {
      page2.drawText(item.label, { x: M, y: y2, size: 10, font: bold, color: darkText });
      const valColor = item.label.startsWith("= Spread") && spread > 0 ? green : item.label.startsWith("= Spread") && spread < 0 ? red : darkText;
      page2.drawText(item.value, { x: M + 200, y: y2, size: 10, font: bold, color: valColor });
      page2.drawText(item.note, { x: M + 320, y: y2, size: 8, font: regular, color: gray });
      y2 -= 20;
    }
    y2 -= 15;

    // --- ASSIGNMENT TERMS ---
    y2 = drawSectionTitle(page2, "ASSIGNMENT TERMS", M, y2, bold, primary, primary, CW);

    const termsText = terms || `Assignment fee: $${actualFee > 0 ? actualFee.toLocaleString() : "Negotiable"}. Subject to buyer inspection and due diligence. Close within 30 days of assignment. Buyer assumes all repair costs and closing fees.`;
    y2 = drawWrappedText(page2, termsText, M, y2, regular, 9, CW, bodyText);
    y2 -= 20;

    // --- IMPORTANT DISCLAIMERS ---
    y2 = drawSectionTitle(page2, "DISCLAIMERS", M, y2, bold, primary, primary, CW);
    const disclaimers = [
      "All financial figures are estimates and subject to independent verification by the buyer.",
      "ARV is based on comparable sales analysis and may vary based on actual market conditions.",
      "Repair estimates are preliminary. Buyer should conduct independent inspection.",
      "This package does not constitute a binding offer or contract.",
    ];
    for (const d of disclaimers) {
      y2 = drawWrappedText(page2, `- ${d}`, M, y2, regular, 8, CW, gray);
      y2 -= 4;
    }

    addFooter(page2);

    const pdfBytes = await pdfDoc.save();

    return new Response(new Uint8Array(pdfBytes).buffer as ArrayBuffer, {
      headers: {
        ...corsHeaders,
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="deal-package-${property?.address?.replace(/\s+/g, '-') || lead_id}.pdf"`,
      },
    });

  } catch (error: unknown) {
    console.error("Error generating deal package:", error);
    const errorMessage = error instanceof Error ? error.message : "Failed to generate deal package";
    return new Response(JSON.stringify({ error: errorMessage }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }
});
